# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7675a8cb6857c26cd61b8a8627671a38a543a1d8ca5a251a7efa17568cd6aec7b8c72e877daa5bda5bccf9c117312770f1949f7588ceca0835ce77b1f9b2c928

test:
  secret_key_base: 1127592b8675fd5ff52496bfcf7ba83168a87b540be26b0d879a5ef0b51f5eadecdbd114fe2b9ca6913a6d22ad264fd322328bcb69189b19e63e8a14392023b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
